main: com.creadri.lazyroad.LazyRoad
version: 0.6
name: LazyRoad
description: Make roads as you walk
author: adreide
website: http://www.creadri.com
commands:
  road:
    description: 'Make roads.'
    usage: |
      /<command>
      /<command> roadName [start count]
      /<command> stop
      /<command> undo
      /<command> straight
  bridge:
    description: 'Make bridges.'
    usage: |
      /<command>
      /<command> roadName pillarName [start count]
      /<command> stop
      /<command> undo
      /<command> straight
  tunnel:
    description: 'Make tunnels.'
    usage: |
      /<command>
      /<command> roadName [start count]
      /<command> stop
      /<command> undo
      /<command> straight
permissions:
  lazyroad.build:
    default: op
    description: Allows users to build roads, bridges and tunnels.