main: com.creadri.lazyroad.LazyRoad
version: 0.5.2
name: LazyRoad
author: adreide
website: http://www.creadri.com
commands:
  road:
    description: 'Make roads.'
    usage: |
      /<command>
      /<command> roadName [start count]
      /<command> stop
      /<command> undo
  bridge:
    description: 'Make bridges.'
    usage: |
      /<command>
      /<command> roadName pillarName [start count]
      /<command> stop
      /<command> undo
  tunnel:
    description: 'Make tunnels.'
    usage: |
      /<command>
      /<command> roadName [start count]
      /<command> stop
      /<command> undo
permissions:
  LazyRoad.build:
    default: op
    description: Allows users to build roads, bridges and tunnels.