main: creadri.LazyRoad.LazyRoad
version: 0.3.2
name: LazyRoad
commands:
  road:
    description: 'Make roads.'
    usage: |
      /<command>
      /<command> roadName <Name block count> <Tunnel mode>
      /<command> stop
      /<command> 